kind = "web"
previewPath = "/conseil-chatbot/"
title = "Monafassa AI Chatbot v2 avec admin panel"
version = "1.0.0"
id = "artifacts/conseil-chatbot"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/conseil-chatbot/" ]
localPort = 21936

[services.development]
run = "pnpm --filter @workspace/conseil-chatbot run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/conseil-chatbot", "run", "build" ]
publicDir = "artifacts/conseil-chatbot/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21936"
BASE_PATH = "/conseil-chatbot/"
